In [0]:
import pandas as pd
import datetime as dt
import calendar 
import statsmodels.api as sm
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
df = pd.read_csv(open('drive/My Drive/Colab Notebooks/lecture folder/Travel Pony Facebook.csv','rb'))
df.head()

   Start Date  ... Cost per Page Engagement (USD)
0  2013-12-02  ...                       1.219512
1  2013-12-01  ...                       1.395349
2  2013-11-30  ...                       1.190476
3  2013-11-29  ...                       1.167315
4  2013-11-22  ...                       2.512857

[5 rows x 20 columns]

In [0]:
df['cost per impression'] = df['Amount Spent (USD)']/df.Impressions
df.head()

   Start Date    End Date  ... Cost per Page Engagement (USD) cost per impression
0  2013-12-02  2013-12-02  ...                       1.219512            0.000466
1  2013-12-01  2013-12-01  ...                       1.395349            0.000652
2  2013-11-30  2013-11-30  ...                       1.190476            0.000448
3  2013-11-29  2013-11-29  ...                       1.167315            0.000452
4  2013-11-22  2013-11-22  ...                       2.512857            0.002464

[5 rows x 21 columns]

In [0]:
df['Start Date']=pd.to_datetime(df['Start Date'])

In [0]:
df['day_of_week'] = df['Start Date'].dt.day_name()
df.head()

  Start Date    End Date  ... cost per impression day_of_week
0 2013-12-02  2013-12-02  ...            0.000466      Monday
1 2013-12-01  2013-12-01  ...            0.000652      Sunday
2 2013-11-30  2013-11-30  ...            0.000448    Saturday
3 2013-11-29  2013-11-29  ...            0.000452      Friday
4 2013-11-22  2013-11-22  ...            0.002464      Friday

[5 rows x 22 columns]

In [0]:
#convert start date into day of the week, making new column 'day of the week'

In [0]:
df.groupby(['day_of_week']) ['cost per impression'].mean().nlargest(1)

day_of_week
Friday    0.004097
Name: cost per impression, dtype: float64

In [0]:
df.groupby(['day_of_week']) ['cost per impression'].mean().nsmallest(1)

day_of_week
Saturday    0.002629
Name: cost per impression, dtype: float64

In [0]:
# group by cost per impression into day of the week, getting the largest and smallest ones.

In [0]:
correlation= df.corr(method ='pearson') 
correlation

                                   Reach  ...  cost per impression
Reach                           1.000000  ...             0.028005
Frequency                       0.334101  ...            -0.018217
Impressions                     0.966851  ...             0.006973
Clicks                          0.709466  ...             0.088315
Unique Clicks                   0.722249  ...             0.086798
Amount Spent (USD)              0.703124  ...             0.119201
Page Likes                      0.304388  ...             0.143931
Page Engagement                 0.597648  ...             0.117141
Post Engagement                 0.605244  ...             0.108649
Post Likes                      0.151727  ...             0.106425
Post Comments                   0.100254  ...             0.074364
Post Shares                     0.153288  ...             0.090520
Photo Views                     0.205678  ...             0.084764
Website Clicks                  0.858860  ...             0.071118
Cost per Page Like (USD)        0.646366  ...             0.088785
Cost per Page Engagement (USD)  0.168697  ...             0.150591
cost per impression             0.028005  ...             1.000000

[17 rows x 17 columns]

In [0]:
correlation.iloc[[0,1,4,6],5]

Reach            0.703124
Frequency        0.130201
Unique Clicks    0.882993
Page Likes       0.757612
Name: Amount Spent (USD), dtype: float64

In [0]:
# Getting the correlation for specific as question asked

In [0]:
dependent = df['Unique Clicks']
Independent = df[['Reach','Frequency']]

mod = sm.OLS(dependent,Independent)
res = mod.fit()
print(res.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:          Unique Clicks   R-squared (uncentered):                   0.557
Model:                            OLS   Adj. R-squared (uncentered):              0.556
Method:                 Least Squares   F-statistic:                              2325.
Date:                Wed, 13 Nov 2019   Prob (F-statistic):                        0.00
Time:                        21:02:57   Log-Likelihood:                         -15973.
No. Observations:                3705   AIC:                                  3.195e+04
Df Residuals:                    3703   BIC:                                  3.196e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Reach          0.0019   3.12e-05     62.490      0.000       0.002       0.002
Frequency      3.6139      0.298     12.109      0.000       3.029       4.199
==============================================================================
Omnibus:                     5107.616   Durbin-Watson:                   0.803
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          5128392.747
Skew:                           7.331   Prob(JB):                         0.00
Kurtosis:                     184.674   Cond. No.                     9.84e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.84e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [0]:
# Running the linear regression